// SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/generate_registry.py from tools/opentherm_ids.py -- DO NOT EDIT.
//
// The web interface is just as much an API client as MQTT and REST. These types describe
// the shape of that API, not the interface's own idea of it.


export interface EntityMeta {
  readonly key: string;
  readonly name: string;
  readonly kind: string;
  readonly dataId: number | null;
  readonly codec: string;
  readonly unit: string | null;
  readonly deviceClass: string | null;
  readonly icon: string | null;
  readonly entityCategory: string | null;
  readonly readable: boolean;
  readonly writable: boolean;
  readonly min: number | null;
  readonly max: number | null;
  readonly options: readonly string[] | null;
}

export const ENTITIES = [
  { key: "ch_setpoint", name: "CH setpoint", kind: "number", dataId: 1, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:thermometer", entityCategory: null, readable: false, writable: true, min: 10.0, max: 90.0, options: null },
  { key: "member_id", name: "Manufacturer member ID", kind: "sensor", dataId: 3, codec: "u8_lb", unit: null, deviceClass: null, icon: "mdi:identifier", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "oem_fault_code", name: "OEM fault code", kind: "sensor", dataId: 5, codec: "u8_lb", unit: null, deviceClass: null, icon: "mdi:numeric", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "remote_override_setpoint", name: "Remote room setpoint", kind: "sensor", dataId: 9, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:thermostat", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "max_relative_modulation", name: "Max relative modulation", kind: "number", dataId: 14, codec: "f88", unit: "%", deviceClass: null, icon: "mdi:speedometer", entityCategory: null, readable: false, writable: true, min: 0.0, max: 100.0, options: null },
  { key: "max_capacity", name: "Max capacity", kind: "sensor", dataId: 15, codec: "u8_hb", unit: "kW", deviceClass: "power", icon: "mdi:lightning-bolt", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "min_modulation", name: "Min modulation", kind: "sensor", dataId: 15, codec: "u8_lb", unit: "%", deviceClass: null, icon: "mdi:speedometer-slow", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "room_setpoint", name: "Room setpoint", kind: "number", dataId: 16, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:home-thermometer", entityCategory: null, readable: false, writable: true, min: 5.0, max: 30.0, options: null },
  { key: "modulation", name: "Modulation level", kind: "sensor", dataId: 17, codec: "f88", unit: "%", deviceClass: null, icon: "mdi:speedometer", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_pressure", name: "CH water pressure", kind: "sensor", dataId: 18, codec: "f88", unit: "bar", deviceClass: "pressure", icon: "mdi:gauge", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_flow_rate", name: "Hot water flow rate", kind: "sensor", dataId: 19, codec: "f88", unit: "L/min", deviceClass: null, icon: "mdi:waves-arrow-right", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "room_temperature", name: "Room temperature", kind: "number", dataId: 24, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:home-thermometer", entityCategory: null, readable: false, writable: true, min: -40.0, max: 60.0, options: null },
  { key: "flow_temperature", name: "Flow temperature", kind: "sensor", dataId: 25, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:thermometer", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_temperature", name: "Hot water temperature", kind: "sensor", dataId: 26, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:water-thermometer", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "outside_temperature", name: "Outside temperature", kind: "sensor", dataId: 27, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:thermometer", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "return_temperature", name: "Return temperature", kind: "sensor", dataId: 28, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:thermometer-minus", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "exhaust_temperature", name: "Exhaust temperature", kind: "sensor", dataId: 33, codec: "s16", unit: "°C", deviceClass: "temperature", icon: "mdi:smoke", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_setpoint_max", name: "Hot water setpoint max", kind: "sensor", dataId: 48, codec: "s8_hb", unit: "°C", deviceClass: "temperature", icon: "mdi:arrow-collapse-up", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_setpoint_min", name: "Hot water setpoint min", kind: "sensor", dataId: 48, codec: "s8_lb", unit: "°C", deviceClass: "temperature", icon: "mdi:arrow-collapse-down", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_setpoint_max_bound", name: "CH setpoint max", kind: "sensor", dataId: 49, codec: "s8_hb", unit: "°C", deviceClass: "temperature", icon: "mdi:arrow-collapse-up", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_setpoint_min_bound", name: "CH setpoint min", kind: "sensor", dataId: 49, codec: "s8_lb", unit: "°C", deviceClass: "temperature", icon: "mdi:arrow-collapse-down", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_setpoint", name: "Hot water setpoint", kind: "number", dataId: 56, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:water-thermometer", entityCategory: null, readable: true, writable: true, min: 30.0, max: 80.0, options: null },
  { key: "max_ch_setpoint", name: "Max CH setpoint", kind: "number", dataId: 57, codec: "f88", unit: "°C", deviceClass: "temperature", icon: "mdi:arrow-collapse-up", entityCategory: null, readable: true, writable: true, min: 30.0, max: 90.0, options: null },
  { key: "unsuccessful_burner_starts", name: "Unsuccessful burner starts", kind: "sensor", dataId: 113, codec: "u16", unit: null, deviceClass: null, icon: "mdi:fire-alert", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "flame_low_signal_count", name: "Flame failures", kind: "sensor", dataId: 114, codec: "u16", unit: null, deviceClass: null, icon: "mdi:fire-off", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "burner_starts", name: "Burner starts", kind: "sensor", dataId: 116, codec: "u16", unit: null, deviceClass: null, icon: "mdi:fire", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_pump_starts", name: "CH pump starts", kind: "sensor", dataId: 117, codec: "u16", unit: null, deviceClass: null, icon: "mdi:pump", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_pump_starts", name: "Hot water pump starts", kind: "sensor", dataId: 118, codec: "u16", unit: null, deviceClass: null, icon: "mdi:pump", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_burner_starts", name: "Hot water burner starts", kind: "sensor", dataId: 119, codec: "u16", unit: null, deviceClass: null, icon: "mdi:fire", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "burner_hours", name: "Burner hours", kind: "sensor", dataId: 120, codec: "u16", unit: "h", deviceClass: "duration", icon: "mdi:clock-outline", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_pump_hours", name: "CH pump hours", kind: "sensor", dataId: 121, codec: "u16", unit: "h", deviceClass: "duration", icon: "mdi:clock-outline", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_pump_hours", name: "Hot water pump hours", kind: "sensor", dataId: 122, codec: "u16", unit: "h", deviceClass: "duration", icon: "mdi:clock-outline", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_burner_hours", name: "Hot water burner hours", kind: "sensor", dataId: 123, codec: "u16", unit: "h", deviceClass: "duration", icon: "mdi:clock-outline", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "master_ot_version", name: "Master OpenTherm version", kind: "number", dataId: 124, codec: "f88", unit: null, deviceClass: null, icon: "mdi:tag", entityCategory: "diagnostic", readable: false, writable: true, min: 0.0, max: 255.0, options: null },
  { key: "slave_ot_version", name: "Boiler OpenTherm version", kind: "sensor", dataId: 125, codec: "f88", unit: null, deviceClass: null, icon: "mdi:tag", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "master_product_version", name: "Master product version", kind: "number", dataId: 126, codec: "u16", unit: null, deviceClass: null, icon: "mdi:tag", entityCategory: "diagnostic", readable: false, writable: true, min: 0.0, max: 65535.0, options: null },
  { key: "slave_product_type", name: "Boiler product type", kind: "sensor", dataId: 127, codec: "u8_hb", unit: null, deviceClass: null, icon: "mdi:tag", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "slave_product_version", name: "Boiler product version", kind: "sensor", dataId: 127, codec: "u8_lb", unit: null, deviceClass: null, icon: "mdi:tag", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "fault", name: "Fault", kind: "binary", dataId: 0, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:alert", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_active", name: "Central heating active", kind: "binary", dataId: 0, codec: "flag", unit: null, deviceClass: "heat", icon: "mdi:radiator", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_active", name: "Hot water active", kind: "binary", dataId: 0, codec: "flag", unit: null, deviceClass: "heat", icon: "mdi:water-boiler", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "flame", name: "Flame on", kind: "binary", dataId: 0, codec: "flag", unit: null, deviceClass: "heat", icon: "mdi:fire", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "cooling_active", name: "Cooling active", kind: "binary", dataId: 0, codec: "flag", unit: null, deviceClass: "cold", icon: "mdi:snowflake", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "diagnostic_indication", name: "Service needed", kind: "binary", dataId: 0, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:wrench", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_present", name: "Hot water present", kind: "binary", dataId: 3, codec: "flag", unit: null, deviceClass: null, icon: "mdi:water", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "control_type_on_off", name: "On/off control", kind: "binary", dataId: 3, codec: "flag", unit: null, deviceClass: null, icon: "mdi:toggle-switch", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "cooling_supported", name: "Cooling supported", kind: "binary", dataId: 3, codec: "flag", unit: null, deviceClass: null, icon: "mdi:snowflake", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_storage_tank", name: "Hot water storage tank", kind: "binary", dataId: 3, codec: "flag", unit: null, deviceClass: null, icon: "mdi:storage-tank", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "pump_control_allowed", name: "Pump control allowed", kind: "binary", dataId: 3, codec: "flag", unit: null, deviceClass: null, icon: "mdi:pump", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "service_request", name: "Service request", kind: "binary", dataId: 5, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:wrench", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "lockout_reset", name: "Lockout reset needed", kind: "binary", dataId: 5, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:lock-reset", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "low_water_pressure", name: "Low water pressure", kind: "binary", dataId: 5, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:gauge-low", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "flame_fault", name: "Flame fault", kind: "binary", dataId: 5, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:fire-off", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "air_pressure_fault", name: "Air pressure fault", kind: "binary", dataId: 5, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:weather-windy", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "water_over_temperature", name: "Water over-temperature", kind: "binary", dataId: 5, codec: "flag", unit: null, deviceClass: "problem", icon: "mdi:thermometer-alert", entityCategory: null, readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_setpoint_transfer_enabled", name: "Hot water setpoint transfer enabled", kind: "binary", dataId: 6, codec: "flag", unit: null, deviceClass: null, icon: "mdi:import", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "max_ch_setpoint_transfer_enabled", name: "Max CH setpoint transfer enabled", kind: "binary", dataId: 6, codec: "flag", unit: null, deviceClass: null, icon: "mdi:import", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "dhw_setpoint_writable", name: "Hot water setpoint writable", kind: "binary", dataId: 6, codec: "flag", unit: null, deviceClass: null, icon: "mdi:pencil", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "max_ch_setpoint_writable", name: "Max CH setpoint writable", kind: "binary", dataId: 6, codec: "flag", unit: null, deviceClass: null, icon: "mdi:pencil", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "override_manual_priority", name: "Manual override priority", kind: "binary", dataId: 100, codec: "flag", unit: null, deviceClass: null, icon: "mdi:hand-back-right", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "override_program_priority", name: "Program override priority", kind: "binary", dataId: 100, codec: "flag", unit: null, deviceClass: null, icon: "mdi:calendar-clock", entityCategory: "diagnostic", readable: true, writable: false, min: null, max: null, options: null },
  { key: "ch_enable", name: "Central heating enabled", kind: "switch", dataId: null, codec: "none", unit: null, deviceClass: null, icon: "mdi:radiator", entityCategory: null, readable: false, writable: true, min: null, max: null, options: null },
  { key: "dhw_enable", name: "Hot water enabled", kind: "switch", dataId: null, codec: "none", unit: null, deviceClass: null, icon: "mdi:water-boiler", entityCategory: null, readable: false, writable: true, min: null, max: null, options: null },
  { key: "heating_season", name: "Heating season", kind: "switch", dataId: null, codec: "none", unit: null, deviceClass: null, icon: "mdi:sun-snowflake-variant", entityCategory: null, readable: false, writable: true, min: null, max: null, options: null },
  { key: "control_mode", name: "Control mode", kind: "enum", dataId: null, codec: "none", unit: null, deviceClass: "enum", icon: "mdi:account-switch", entityCategory: null, readable: false, writable: false, min: null, max: null, options: ["local", "ha"] },
  { key: "control_state", name: "Control state", kind: "enum", dataId: null, codec: "none", unit: null, deviceClass: "enum", icon: "mdi:state-machine", entityCategory: null, readable: false, writable: false, min: null, max: null, options: ["season_off", "boost", "local", "ha_waiting", "failsafe", "ha"] },
  { key: "ch_setpoint_effective", name: "Effective CH setpoint", kind: "sensor", dataId: null, codec: "none", unit: "°C", deviceClass: "temperature", icon: "mdi:thermometer", entityCategory: null, readable: false, writable: false, min: null, max: null, options: null },
  { key: "room_temperature_effective", name: "Room temperature", kind: "sensor", dataId: null, codec: "none", unit: "°C", deviceClass: "temperature", icon: "mdi:home-thermometer", entityCategory: null, readable: false, writable: false, min: null, max: null, options: null },
  { key: "room_source", name: "Room source", kind: "enum", dataId: null, codec: "none", unit: null, deviceClass: null, icon: "mdi:home-search", entityCategory: null, readable: false, writable: false, min: null, max: null, options: ["none", "shield", "mqtt"] },
  { key: "ch_enable_effective", name: "Heat demand to boiler", kind: "binary", dataId: null, codec: "none", unit: null, deviceClass: null, icon: "mdi:radiator", entityCategory: null, readable: false, writable: false, min: null, max: null, options: null },
  { key: "failsafe_count", name: "Failsafe entries", kind: "sensor", dataId: null, codec: "none", unit: null, deviceClass: null, icon: "mdi:shield-alert", entityCategory: "diagnostic", readable: false, writable: false, min: null, max: null, options: null },
  { key: "last_failsafe_duration_s", name: "Last failsafe duration", kind: "sensor", dataId: null, codec: "none", unit: "s", deviceClass: "duration", icon: "mdi:timer-alert-outline", entityCategory: "diagnostic", readable: false, writable: false, min: null, max: null, options: null },
] as const satisfies readonly EntityMeta[];

// Derived, not listed a second time: a hand-written union of the keys would be
// exactly that second list of entities which CLAUDE.md forbids.
export type EntityKey = (typeof ENTITIES)[number]["key"];
export type EntityKind = (typeof ENTITIES)[number]["kind"];

// Availability has three values. DATA-INVALID and UNKNOWN-DATAID are different
// diagnoses: the first means "supported, no data", the second "no such thing at all".
export type Availability = "ok" | "invalid" | "unsupported" | "unknown";

// A string is an enum's option: ot_api renders the option, never its index.
export type EntityValue = number | boolean | string | null;

export interface StateEntry {
  readonly value: EntityValue;
  readonly availability: Availability;
  readonly ageMs: number | null;
}

export type State = Partial<Record<EntityKey, StateEntry>>;

export const SCHEMA_VERSION = 1;
