// SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
// SPDX-License-Identifier: Apache-2.0

#include "web_assets.h"

// Symbol names are generated by EMBED_FILES from the file names: dots and
// slashes become underscores, with _binary_ prefix and _start/_end suffixes.
extern const unsigned char index_html_gz_start[] asm("_binary_index_html_gz_start");
extern const unsigned char index_html_gz_end[]   asm("_binary_index_html_gz_end");
extern const unsigned char app_js_gz_start[]     asm("_binary_app_js_gz_start");
extern const unsigned char app_js_gz_end[]       asm("_binary_app_js_gz_end");
extern const unsigned char style_css_gz_start[]  asm("_binary_style_css_gz_start");
extern const unsigned char style_css_gz_end[]    asm("_binary_style_css_gz_end");

static web_asset_t s_assets[4];

const web_asset_t *web_assets(void)
{
    s_assets[0] = (web_asset_t){"/", "text/html", index_html_gz_start,
                                (size_t)(index_html_gz_end - index_html_gz_start)};
    s_assets[1] = (web_asset_t){"/app.js", "application/javascript", app_js_gz_start,
                                (size_t)(app_js_gz_end - app_js_gz_start)};
    s_assets[2] = (web_asset_t){"/style.css", "text/css", style_css_gz_start,
                                (size_t)(style_css_gz_end - style_css_gz_start)};
    s_assets[3] = (web_asset_t){0};
    return s_assets;
}
