# SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
# SPDX-License-Identifier: Apache-2.0

"""Home Assistant discovery, rendered from the single list.

Output: components/ot_ha/include/ha_generated.h -- one TEMPLATED JSON document per Home
Assistant entity. The document's whole shape is decided HERE, from build_entities(); the
firmware only fills six tokens at runtime (ot_ha_render(), components/ot_ha/ot_ha.c):

    {P}  the topic prefix, JSON-escaped, inside a string   "opentherm/aabbccddeeff"
    {I}  the device id, twelve lower-case hex characters   "aabbccddeeff"
    {D}  the device block, a JSON object                   {"ids":[...],"name":...}
    {O}  the origin block, a JSON object                   {"name":"opentherm-thermostat"}
    {L}  the minimum of a number, a JSON number             40 / 45.5
    {H}  the maximum of a number, a JSON number             70

A token is a brace, one capital letter and a brace. Compact JSON never contains that outside a
string, and test_discovery.py forbids a brace inside every static string, so a token cannot be
mistaken for text. expand() below is the Python statement of the same six rules: the tests
expand every document with it and hand the result to json.loads() and to Home Assistant's own
validating schemas (test_ha_schema.py); test_ot_ha pins the C expander to the same bytes.

THE FIVE RULES THAT KILL AN ENTITY SILENTLY (carried over from the ComfoAir firmware's
discovery design; each has a test in test_discovery.py, and test_ha_schema.py asks HA itself):

1. `options` needs `device_class: enum` and forbids `unit_of_measurement` and `state_class`
   (homeassistant/components/mqtt/sensor.py). Our two enums are CLOSED sets -- ot_state refuses
   an index outside the options and ot_api renders null for none -- so they DO publish options.
2. A feature HA reads as a pair is published whole or not at all: a command-bearing component
   always has its command topic, and a gated entity always has both availability topics AND
   availability_mode "all" -- one of the two alone is an entity that is never unavailable.
3. Topic segments are [a-zA-Z0-9_-] only (mqtt/discovery.py, TOPIC_MATCHER): the node is the
   bare hex id, the object id the registry key; the colons of a MAC live inside `dev` only.
4. `configuration_url` is validated as a URL with a scheme (cv.configuration_url), and a
   rejected device block takes the whole entity with it: absent when there is no address.
5. Absent metadata is omitted, never published as "" -- "" is a unit, a class, a name.
"""
import json

from registry_model import CONTROLS, build_entities

BANNER = """// SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/generate_registry.py (tools/render_discovery.py) from
// tools/opentherm_ids.py -- DO NOT EDIT.
//
// One templated Home Assistant discovery document per entity. The tokens {P} {I} {D} {O} {L}
// {H} are filled by ot_ha_render(); render_discovery.py says what each one is.
"""

DISCOVERY_PREFIX = "homeassistant"   # HA's default; it is where HA listens, not our own tree
ORIGIN_NAME = "opentherm-thermostat"

TOKENS = {"prefix": "{P}", "id": "{I}", "device": "{D}", "origin": "{O}",
          "min": "{L}", "max": "{H}"}

# ot_ha_bounds_t, in this order: APPEND ONLY.
BOUNDS = ("none", "flow", "state")

# The command a switch or a number is, by its registry control number.
_CONTROL = {v: k for k, v in CONTROLS.items()}

# How HA may send a command, per control command. The flow setpoint takes its
# bounds from the runtime flow band; the DHW setpoint from the boiler's ID 48,
# through ot_state_bounds(). Steps: ot_control quantises a CH setpoint to 0.5 °C; the DHW
# setpoint is whole degrees, because a boiler that keeps whole degrees would otherwise start
# the DHW-setpoint reconciliation on every half-degree HA sends.
_NUMBER = {"CH_SETPOINT": ("flow", 0.5), "DHW_SETPOINT": ("state", 1)}

# HA may turn these OFF and never ON (ot_control refuses the other way
# with OT_CONTROL_SEASON_ON_IS_LOCAL). A switch would snap back when turned on, so HA gets a
# binary_sensor for the state and a button for the one command it may send.
_OFF_ONLY = {"SEASON"}

# The one entity with JSON attributes: control_state carries its reason and cause.
_ATTRIBUTES = {"control_state"}

# Payloads. A state is what ot_api renders -- true/false, a number, an enum's option -- so a
# switch reads "true"/"false" and is commanded with "1"/"0", the numbers ot_command_check()
# takes. The button's press is "0": the season's one legal command from HA.
ON_STATE, OFF_STATE = "true", "false"
ON_COMMAND, OFF_COMMAND = "1", "0"


class Doc:
    """One discovery document: where it goes, when it is wanted, and its templated body."""

    def __init__(self, entity_index, component, object_id, gated, wire, bounds, body):
        self.entity_index = entity_index
        self.component = component
        self.object_id = object_id
        self.gated = gated
        self.wire = wire
        self.bounds = bounds
        self.body = body          # a dict; tokens are plain strings in it


def _topic(key, leaf):
    return f"{TOKENS['prefix']}/{key}/{leaf}"


def _base(e, component, object_id, gated):
    body = {
        "name": e.name,
        "uniq_id": f"{TOKENS['id']}_{object_id}",
        # The entity id HA creates the first time it sees the entity; HA's own default would
        # slugify the Russian name. Stable English ids are what automations (V3) refer to.
        "def_ent_id": f"{component}.opentherm_{object_id}",
    }
    if gated:
        # Rule 2: both topics AND "all", or the entity is never unavailable.
        body["avty"] = [{"t": f"{TOKENS['prefix']}/status"},
                        {"t": f"{TOKENS['prefix']}/control/owner"}]
        body["avty_mode"] = "all"
    else:
        body["avty_t"] = f"{TOKENS['prefix']}/status"
    if e.icon:
        body["ic"] = e.icon
    if e.entity_category:
        body["ent_cat"] = e.entity_category
    body["dev"] = TOKENS["device"]
    body["o"] = TOKENS["origin"]
    return body


def _put(body, key, value):
    """Rule 5: an absent value is no key at all."""
    if value is not None and value != "":
        body[key] = value


def _sensor(e, i, wire):
    body = _base(e, "sensor", e.key, False)
    body["stat_t"] = _topic(e.key, "state")
    if e.kind == "enum":
        # Rule 1: options with device_class enum, and no unit or state class.
        body["dev_cla"] = "enum"
        body["ops"] = list(e.options)
    else:
        _put(body, "dev_cla", e.device_class)
        _put(body, "stat_cla", e.state_class)
        _put(body, "unit_of_meas", e.unit)
    if e.key in _ATTRIBUTES:
        body["json_attr_t"] = _topic(e.key, "attributes")
    return Doc(i, "sensor", e.key, False, wire, "none", body)


def _binary(e, i, wire, object_id=None):
    object_id = object_id or e.key
    body = _base(e, "binary_sensor", object_id, False)
    body["stat_t"] = _topic(e.key, "state")
    body["pl_on"], body["pl_off"] = ON_STATE, OFF_STATE
    _put(body, "dev_cla", e.device_class)
    return Doc(i, "binary_sensor", object_id, False, wire, "none", body)


def _switch(e, i):
    body = _base(e, "switch", e.key, True)
    body["stat_t"] = _topic(e.key, "state")
    body["cmd_t"] = _topic(e.key, "set")
    body["pl_on"], body["pl_off"] = ON_COMMAND, OFF_COMMAND
    body["stat_on"], body["stat_off"] = ON_STATE, OFF_STATE
    return Doc(i, "switch", e.key, True, False, "none", body)


def _number(e, i, command, wire):
    bounds, step = _NUMBER[command]
    body = _base(e, "number", e.key, True)
    body["stat_t"] = _topic(e.key, "state")
    body["cmd_t"] = _topic(e.key, "set")
    body["min"], body["max"] = TOKENS["min"], TOKENS["max"]
    body["step"] = step
    body["mode"] = "box"
    _put(body, "unit_of_meas", e.unit)
    _put(body, "dev_cla", e.device_class)
    return Doc(i, "number", e.key, True, wire, bounds, body)


def _off_button(e, i):
    object_id = f"{e.key}_off"
    body = _base(e, "button", object_id, True)
    body["cmd_t"] = _topic(e.key, "set")
    body["pl_prs"] = OFF_COMMAND
    return Doc(i, "button", object_id, True, False, "none", body)


def build_docs() -> list[Doc]:
    """Every document, in registry order. What is NOT here is decided here too:

    * a write-only frame row (IDs 14, 16, 24, 124, 126) has no state and no HA command --
      16 and 24 are kept away from HA, and 14, 124 and 126 are the firmware's own;
    * `wire` marks a row read from the boiler: ot_ha_want() waits until its Data-ID has been
      answered and drops it once the boiler says UNKNOWN-DATAID ("IDs the boiler does
      not support are skipped"). A control entity is never `wire`: ID 1's unsupported flag
      never clears and must not hide the setpoint HA commands.
    """
    docs: list[Doc] = []
    for i, e in enumerate(build_entities()):
        command = _CONTROL.get(e.control)
        from_wire = e.data_id is not None and e.readable
        if command in _OFF_ONLY:
            docs.append(_binary(e, i, False))
            docs.append(_off_button(e, i))
        elif command in _NUMBER:
            docs.append(_number(e, i, command, from_wire))
        elif command is not None:
            docs.append(_switch(e, i))
        elif e.data_id is None or e.readable:
            if e.kind in ("binary", "switch"):
                docs.append(_binary(e, i, from_wire))
            else:
                docs.append(_sensor(e, i, from_wire))
    return docs


def template(doc: Doc) -> str:
    """The body as compact ASCII JSON, with the four non-string tokens unquoted."""
    text = json.dumps(doc.body, ensure_ascii=True, separators=(",", ":"))
    for token in (TOKENS["device"], TOKENS["origin"], TOKENS["min"], TOKENS["max"]):
        text = text.replace(f'"{token}"', token)
    return text


def number_text(dc: int) -> str:
    """Tenths of a degree as a JSON number: 400 -> 40, 455 -> 45.5, -5 -> -0.5."""
    sign = "-" if dc < 0 else ""
    whole, tenth = divmod(abs(dc), 10)
    return f"{sign}{whole}" + (f".{tenth}" if tenth else "")


def device_block(ctx: dict) -> str:
    """The {D} object. ctx: device_id, mac, name, model, sw_version, ip -- "" omits."""
    dev = {"ids": [ctx["device_id"]]}
    if ctx["mac"]:
        dev["cns"] = [["mac", ctx["mac"]]]
    dev["name"] = ctx["name"]
    _put(dev, "mdl", ctx["model"])
    _put(dev, "sw", ctx["sw_version"])
    if ctx["ip"]:
        dev["cu"] = f"http://{ctx['ip']}/"      # rule 4: a scheme, or no key at all
    return json.dumps(dev, ensure_ascii=True, separators=(",", ":"))


def origin_block(ctx: dict) -> str:
    origin = {"name": ORIGIN_NAME}
    _put(origin, "sw", ctx["sw_version"])
    return json.dumps(origin, ensure_ascii=True, separators=(",", ":"))


def expand(text: str, ctx: dict, lo_dc: int = 0, hi_dc: int = 0) -> str:
    """The Python statement of ot_ha_render(): the same six substitutions."""
    prefix = json.dumps(ctx["prefix"], ensure_ascii=True)[1:-1]
    return (text.replace(TOKENS["prefix"], prefix)
                .replace(TOKENS["id"], ctx["device_id"])
                .replace(TOKENS["device"], device_block(ctx))
                .replace(TOKENS["origin"], origin_block(ctx))
                .replace(TOKENS["min"], number_text(lo_dc))
                .replace(TOKENS["max"], number_text(hi_dc)))


def _c_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_discovery() -> str:
    docs = build_docs()
    lines = [BANNER, "#pragma once", "",
             "#include <stdbool.h>", "#include <stdint.h>", "",
             "#ifdef __cplusplus", 'extern "C" {', "#endif", "",
             f'#define OT_HA_DISCOVERY_PREFIX "{DISCOVERY_PREFIX}"',
             f'#define OT_HA_ORIGIN_NAME "{ORIGIN_NAME}"', "",
             "typedef enum {"]
    lines += [f"    OT_HA_BOUNDS_{b.upper()}," for b in BOUNDS]
    lines += ["} ot_ha_bounds_t;", "",
              "typedef struct {",
              "    uint16_t    entity;      // index into OT_ENTITIES",
              '    const char *component;   // "sensor", "binary_sensor", "switch", "number", "button"',
              "    const char *object_id;   // the discovery topic's last segment, [a-z0-9_]",
              "    bool        gated;       // available only while HA owns the controls",
              "    bool        wire;        // read from the boiler: wait for an answer, drop if unsupported",
              "    uint8_t     bounds;      // ot_ha_bounds_t: where {L} and {H} come from",
              "    const char *body;        // the templated document",
              "} ot_ha_doc_t;", "",
              f"enum {{ OT_HA_DOC_COUNT = {len(docs)} }};", "",
              "static const ot_ha_doc_t OT_HA_DOCS[OT_HA_DOC_COUNT] = {"]
    for d in docs:
        lines += [
            "    {",
            f"        .entity = {d.entity_index},",
            f"        .component = {_c_str(d.component)},",
            f"        .object_id = {_c_str(d.object_id)},",
            f"        .gated = {'true' if d.gated else 'false'},",
            f"        .wire = {'true' if d.wire else 'false'},",
            f"        .bounds = OT_HA_BOUNDS_{d.bounds.upper()},",
            f"        .body = {_c_str(template(d))},",
            "    },",
        ]
    lines += ["};", "", "#ifdef __cplusplus", "}", "#endif", ""]
    return "\n".join(lines)
