# SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
# SPDX-License-Identifier: Apache-2.0

"""The C renderer: the model into components/ot_registry/include/registry_generated.h.

Only the C projection lives here -- its literals (NULL, NAN, the "|"-joined options), its
banner and its layout of ot_entity_t. The rows, their validation and the poll ring are
registry_model.py's; generate_registry.py decides where the text is written.
"""
from registry_model import CODECS, KINDS, build_entities, table

BANNER_C = """// SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/generate_registry.py from tools/opentherm_ids.py -- DO NOT EDIT.
//
// Edit the table and regenerate. An edit here is a second list of entities, which
// CLAUDE.md forbids, and it will be silently undone by the next build.
"""

OPTION_SEP = "|"  # joins an enum's options; emitted as OT_OPTION_SEP, C splits on it


def c_str(value) -> str:
    """A C string literal or NULL. Missing metadata is NULL, not "", so that the
    consumer can tell "no unit" from "an empty unit"."""
    if value is None:
        return "NULL"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def c_bool(value: bool) -> str:
    return "true" if value else "false"


def c_float(value) -> str:
    """NaN, not 0.0. Zero would mean "a range from zero to zero" for every entity that
    has no range, and would diverge from null in the TypeScript projection."""
    return "NAN" if value is None else f"{float(value)}f"


def render_c_header() -> str:
    entities = build_entities()
    lines = [BANNER_C, "#pragma once", "",
             "#include <math.h>",       # NAN for entities without a range
             "#include <stdbool.h>",
             "#include <stddef.h>",
             "#include <stdint.h>", "",
             "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]

    lines.append("typedef enum {")
    for kind in KINDS:
        lines.append(f"    OT_KIND_{kind.upper()},")
    lines += ["} ot_entity_kind_t;", ""]

    lines.append("typedef enum {")
    for codec in CODECS:
        lines.append(f"    OT_CODEC_{codec.upper()},")
    lines += ["} ot_codec_kind_t;", ""]
    lines += [f"#define OT_OPTION_SEP '{OPTION_SEP}'   // between the options of an enum", ""]

    lines += [
        "typedef struct {",
        "    const char *key;              // stable identifier: API path, MQTT topic, object_id",
        "    const char *name;             // human-readable name",
        "    ot_entity_kind_t kind;",
        "    int16_t data_id;              // 0..127; -1: synthetic, no Data-ID",
        "    ot_codec_kind_t codec;",
        "    bool flag_high_byte;          // meaningful when OT_CODEC_FLAG",
        "    uint8_t flag_bit;             // 0..7, meaningful when OT_CODEC_FLAG",
        "    bool readable;                // takes part in the poll ring",
        "    bool writable;",
        "    uint8_t control;              // 0: none, else an ot_control_cmd_t (ot_control.h)",
        "    int16_t write_id;             // -1 when it coincides with data_id",
        "    int16_t bounds_from;          // the Data-ID of the bounds; -1 when there are none",
        "    const char *unit;",
        "    const char *device_class;",
        "    const char *state_class;",
        "    const char *icon;",
        "    const char *entity_category;",
        '    const char *options;          // "local|ha"; NULL unless kind is OT_KIND_ENUM',
        "    float min_value;              // NaN when the table gives no range",
        "    float max_value;",
        "    float default_value;",
        "} ot_entity_t;",
        "",
    ]

    lines.append(f"enum {{ OT_ENTITY_COUNT = {len(entities)} }};")
    lines.append("")
    lines.append("static const ot_entity_t OT_ENTITIES[OT_ENTITY_COUNT] = {")
    for e in entities:
        lines += [
            "    {",
            f"        .key = {c_str(e.key)},",
            f"        .name = {c_str(e.name)},",
            f"        .kind = OT_KIND_{e.kind.upper()},",
            f"        .data_id = {e.data_id if e.data_id is not None else -1},",
            f"        .codec = OT_CODEC_{e.codec.upper()},",
            f"        .flag_high_byte = {c_bool(e.flag_high_byte)},",
            f"        .flag_bit = {e.flag_bit},",
            f"        .readable = {c_bool(e.readable)},",
            f"        .writable = {c_bool(e.writable)},",
            f"        .control = {e.control},",
            f"        .write_id = {e.write_id if e.write_id is not None else -1},",
            f"        .bounds_from = {e.bounds_from if e.bounds_from is not None else -1},",
            f"        .unit = {c_str(e.unit)},",
            f"        .device_class = {c_str(e.device_class)},",
            f"        .state_class = {c_str(e.state_class)},",
            f"        .icon = {c_str(e.icon)},",
            f"        .entity_category = {c_str(e.entity_category)},",
            f"        .options = {c_str(OPTION_SEP.join(e.options) if e.options else None)},",
            f"        .min_value = {c_float(e.min_value)},",
            f"        .max_value = {c_float(e.max_value)},",
            f"        .default_value = {c_float(e.default)},",
            "    },",
        ]
    lines += ["};", ""]

    ids = table.POLL_IDS
    lines.append("// The poll ring apart from the mandatory ID 0: the scheduler sends it")
    lines.append("// on every second step, and its presence here would double its rate.")
    lines.append(f"enum {{ OT_POLL_ID_COUNT = {len(ids)} }};")
    lines.append("static const uint8_t OT_POLL_IDS[] = {")
    for i in range(0, len(ids), 12):
        lines.append("    " + ", ".join(str(x) for x in ids[i:i + 12]) + ",")
    lines += ["};", ""]

    lines += [
        f"enum {{ OT_SCHEMA_VERSION = {table.SCHEMA_VERSION} }};",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    return "\n".join(lines)
