# SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
# SPDX-License-Identifier: Apache-2.0

"""The TypeScript renderer: the model into web/src/api/entities.ts.

Only the TS projection lives here -- its literals (null, the options as an array), its banner
and the types the SPA derives from ENTITIES. The rows are registry_model.py's;
generate_registry.py decides where the text is written.
"""
from registry_model import build_entities, table

BANNER_TS = """// SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/generate_registry.py from tools/opentherm_ids.py -- DO NOT EDIT.
//
// The web interface is just as much an API client as MQTT and REST. These types describe
// the shape of that API, not the interface's own idea of it.
"""


def ts_str(value) -> str:
    if value is None:
        return "null"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_ts_types() -> str:
    entities = build_entities()
    lines = [BANNER_TS, ""]
    lines += [
        "export interface EntityMeta {",
        "  readonly key: string;",
        "  readonly name: string;",
        "  readonly kind: string;",
        "  readonly dataId: number | null;",
        "  readonly codec: string;",
        "  readonly unit: string | null;",
        "  readonly deviceClass: string | null;",
        "  readonly icon: string | null;",
        "  readonly entityCategory: string | null;",
        "  readonly readable: boolean;",
        "  readonly writable: boolean;",
        "  readonly min: number | null;",
        "  readonly max: number | null;",
        "  readonly options: readonly string[] | null;",
        "}",
        "",
        "export const ENTITIES = [",
    ]
    for e in entities:
        lines.append(
            "  { "
            f"key: {ts_str(e.key)}, name: {ts_str(e.name)}, kind: {ts_str(e.kind)}, "
            f"dataId: {e.data_id if e.data_id is not None else 'null'}, "
            f"codec: {ts_str(e.codec)}, unit: {ts_str(e.unit)}, "
            f"deviceClass: {ts_str(e.device_class)}, icon: {ts_str(e.icon)}, "
            f"entityCategory: {ts_str(e.entity_category)}, "
            f"readable: {str(e.readable).lower()}, "
            f"writable: {str(e.writable).lower()}, "
            f"min: {e.min_value if e.min_value is not None else 'null'}, "
            f"max: {e.max_value if e.max_value is not None else 'null'}, "
            f"options: {'[' + ', '.join(map(ts_str, e.options)) + ']' if e.options else 'null'} }},"
        )
    lines += ["] as const satisfies readonly EntityMeta[];", ""]

    lines += [
        "// Derived, not listed a second time: a hand-written union of the keys would be",
        "// exactly that second list of entities which CLAUDE.md forbids.",
        'export type EntityKey = (typeof ENTITIES)[number]["key"];',
        'export type EntityKind = (typeof ENTITIES)[number]["kind"];',
        "",
        "// Availability has three values. DATA-INVALID and UNKNOWN-DATAID are different",
        "// diagnoses: the first means \"supported, no data\", the second \"no such thing at all\".",
        'export type Availability = "ok" | "invalid" | "unsupported" | "unknown";',
        "",
        "// A string is an enum's option: ot_api renders the option, never its index.",
        "export type EntityValue = number | boolean | string | null;",
        "",
        "export interface StateEntry {",
        "  readonly value: EntityValue;",
        "  readonly availability: Availability;",
        "  readonly ageMs: number | null;",
        "}",
        "",
        "export type State = Partial<Record<EntityKey, StateEntry>>;",
        "",
        f"export const SCHEMA_VERSION = {table.SCHEMA_VERSION};",
        "",
    ]
    return "\n".join(lines)
