# SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
# SPDX-License-Identifier: Apache-2.0

"""Renders web/src/i18n/entityNames.generated.ts: the entity display names in every language.

English is the canonical name from opentherm_ids.py (what Home Assistant sees); DE/NL/UK come
from entity_names_i18n.py. The web's language switcher reads this table; Home Assistant does
not -- it is a web-only overlay.

This renderer is the guard that keeps entity_names_i18n.py from drifting: it raises (failing
generation, and so the build) unless every registry entity has all three translations and no
translation names an entity that no longer exists.
"""
from entity_names_i18n import ENTITY_NAMES_I18N, LOCALES
from registry_model import build_entities
from render_ts import ts_str

BANNER = """// SPDX-FileCopyrightText: 2026 Oleksandr Slukovskyi (@blade-running-man)
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/generate_registry.py (tools/render_entity_names_ts.py)
// from tools/opentherm_ids.py + tools/entity_names_i18n.py -- DO NOT EDIT.
//
// Entity display names in every UI language. English is the canonical name (the one Home
// Assistant sees via discovery); DE/NL/UK are the web-only overlay. Consumed by
// web/src/i18n/entityName.ts. Fix the generator, never this file.
"""


def _validate(keys: list[str]) -> None:
    registry = set(keys)
    translated = set(ENTITY_NAMES_I18N)
    missing = registry - translated
    orphan = translated - registry
    if missing:
        raise ValueError(
            "entity_names_i18n.py is missing translations for: "
            + ", ".join(sorted(missing))
        )
    if orphan:
        raise ValueError(
            "entity_names_i18n.py translates keys that are not entities: "
            + ", ".join(sorted(orphan))
        )
    for key, row in ENTITY_NAMES_I18N.items():
        for loc in LOCALES:
            if not row.get(loc, "").strip():
                raise ValueError(f'entity_names_i18n.py: "{key}" has no "{loc}" name')


def render_entity_names_ts() -> str:
    entities = build_entities()
    _validate([e.key for e in entities])

    lines = [BANNER, ""]
    lines.append(
        "export const ENTITY_NAMES: "
        "Record<string, { en: string; de: string; nl: string; uk: string }> = {"
    )
    for e in entities:
        tr = ENTITY_NAMES_I18N[e.key]
        lines.append(
            f"  {ts_str(e.key)}: {{ en: {ts_str(e.name)}, "
            f"de: {ts_str(tr['de'])}, nl: {ts_str(tr['nl'])}, uk: {ts_str(tr['uk'])} }},"
        )
    lines += ["} as const;", ""]
    return "\n".join(lines)
